### ISSUE TITLE
How create admin account?

### ISSUE THREAD

**Issue by martinjanda** [sachinkale/hotelonrails#2]
This project looks promising for the future. I'm trying to just your PC. I do not know how I create the admin account?

**Comment by sachinkale** [comment]
creating admin account via frontent is still not done. 
You can create it via rails console.
See "Devise" for more details as this project uses it for user/admin session managment

**Comment by geckozo6** [comment]
In the rails application directory what you have to execute is the next:

rails c

once you are in rails console mode then you have to execute the next code but changing that parameters for yours and everything will be great, only thing you need to do is login in the hotelonrails application.

User.create!({:email => "yourmail", :roles => ["admin"], :password => "yourpass", :password_confirmation => "yourpass" })

I know you already do it, but I think that there is more people with the same question.

Best Regards!
