### ISSUE TITLE
Admin

### ISSUE THREAD

**Issue by mariusv** [sachinkale/hotelonrails#3]
How do you create an admin or user?

**Comment by mariusv** [comment]
Never mind..I'm stupid :) sorry

**Comment by geckozo6** [comment]
In the rails application directory what you have to execute is the next:

rails c 

once you are in rails console mode then you have to execute the next code but changing that parameters for yours and everything will be great, only thing you need to do is login in the hotelonrails application.

User.create!({:email => "yourmail", :roles => ["admin"], :password => "yourpass", :password_confirmation => "yourpass" })

I know you already do it, but I think that there is more people with the same question.

Best Regards!
